In [1]:
import os
import pandas as pd 
from pycaret.regression import *

In [2]:
features = ['age','bmi','children','smoker']
target = 'charges'

In [3]:
data = pd.read_csv('../data/insurance.csv')
data = data[[*features,target]]
data

      age     bmi  children smoker      charges
0      19  27.900         0    yes  16884.92400
1      18  33.770         1     no   1725.55230
2      28  33.000         3     no   4449.46200
3      33  22.705         0     no  21984.47061
4      32  28.880         0     no   3866.85520
...   ...     ...       ...    ...          ...
1333   50  30.970         3     no  10600.54830
1334   18  31.920         0     no   2205.98080
1335   18  36.850         0     no   1629.83350
1336   21  25.800         0     no   2007.94500
1337   61  29.070         0    yes  29141.36030

[1338 rows x 5 columns]

In [5]:
s = setup(data,target='charges',session_id=2023)

In [6]:
best_model = compare_models()